### PR TITLE
pre-v1.0.0 tweaks

### PR DESCRIPTION
**Pull request by og113**
Shrunk logo on README, following change on WallGoCollision. Other v1 tweaks; feel free to add your own.

Made a bunch of updates to the API docs, which you can see here:
https://wallgo.readthedocs.io/en/shrinklogo/

### CODE REVIEW

**Comment by og113** [comment]
Looking through the WallGo docs, there are quite a few things I would want to update. The docs seem rather out of date with the paper. This should ideally be done before v1.0.0, because the doc strings are in the code.

**Comment by og113** [comment]
In summary, the following are docs strings things in WallGo that could do with a bit of work:
- [ ] PotentialTools: doesn't give an equation in the docs for the exact one-loop thing that is calculated
- [ ] boltzmann: missing particle index, plus indices don't match paper
- [ ] collisionArray: indices again
- [ ] effectivePotential, I found the V(0) thing confusing
- [ ] EOM, say "equation of motion" in the text
- [ ] freeEnergy, need to show differential evolution equation for tracePhase
- [ ] grid, indices
- [ ] hydro, some unmatched parenthesis
- [ ] manager, we have stuff like "good for hiding from the user" which should be rewritten as though addressed to the user e.g. "to help with ..."
- [ ] particle, some equation like "m^2=m_0^2+m_T^2" would be useful
- [ ] polynomial, indices
- [ ] results, could do with more tex stuff to describe the quantities

**Review by benoitlaurent96 — APPROVED** [review]
I think the documentation looks really great, thanks for making all these edits Oli! If you don't see anything else that can be improved, I think it would be fine to merge it in main.

**Review by benoitlaurent96 — CHANGES_REQUESTED** [review]
I just noticed that I don't see the logo on the main page. Instead, I get the text "<img src="docs/source/figures/wallgo.svg" alt="WallGoLogo" width="200"/".

**Comment by og113** [comment]
> I just noticed that I don't see the logo on the main page. Instead, I get the text "WallGoLogo` at the end.

**Review by joonashir — APPROVED** [review]

**Comment by og113** [comment]
> I just noticed that I don't see the logo on the main page. Instead, I get the text "<img src="docs/source/figures/wallgo.svg" alt="WallGoLogo" width="200"/".

This has now been fixed, by Joonas.

**Review by benoitlaurent96 — APPROVED** [review]

**Pull request merged**
