### PR TITLE
Phase tracing options

### PR DESCRIPTION
**Pull request by og113**
Added one option for setting the first step size in phase tracing. Option can be fixed with config.
```
 phaseTracerFirstStep: float | None = None
  r"""
  Starting step for phaseTrace. If a float, this gives the starting step
  size in units of the maximum step size :py:data:`dT`. If :py:data:`None` then
  uses the initial step size algorithm of :py:mod:`scipy.integrate.solve_ivp`.
  """
```

In the model files, I've put the option to `None` for all the models except the Standard Model, where I have set it to `1.0`. Is this correct? I couldn't quite remember.

### CODE REVIEW

**Comment by jorindevandevis** [comment]
Great, for the SM I can now reproduce the results we had in the draft earlier. 
But I'm a little bit confused about this, because when we obtained them earlier, we used the default initial step size, and on main we use the maximum step size, right?

**Comment by jorindevandevis** [comment]
Also the model file from one of the beta testers that we had trouble with earlier works without modifications, which is very good!

**Comment by og113** [comment]
> Great, for the SM I can now reproduce the results we had in the draft earlier. But I'm a little bit confused about this, because when we obtained them earlier, we used the default initial step size, and on main we use the maximum step size, right?

I actually don't know what version of the code the SM results in our paper were produced with. I thought that they weren't produced with v1.0.0 but I could be wrong.

**Comment by jorindevandevis** [comment]
No, indeed, the graph was not made with v.1.0.0.
I think I misunderstood the description above. Does None or 1.0 give the v.1.0.0 behavior?

**Comment by og113** [comment]
Looks to me like v1.0.0 is equivalent to `phaseTracerFirstStep=1`.

See:
https://github.com/Wall-Go/WallGo/blob/aa3f43e8ee15648b0e55f1f8ece2ac7fb1e73c28/src/WallGo/freeEnergy.py#L420

**Comment by jorindevandevis** [comment]
> Added one option for setting the first step size in phase tracing. Option can be fixed with config.
> 
> ```
>  phaseTracerFirstStep: float | None = None
>   r"""
>   Starting step for phaseTrace. If a float, this gives the starting step
>   size in units of the maximum step size :py:data:`dT`. If :py:data:`None` then
>   uses the initial step size algorithm of :py:mod:`scipy.integrate.solve_ivp`.
>   """
> ```
> 
> In the model files, I've put the option to `None` for all the models except the Standard Model, where I have set it to `1.0`. Is this correct? I couldn't quite remember.

Ahhhh now I see why I was confused. For the SM it is actually set to None, not to 1.0. None is indeed the right value, so I was confused why this would work with 1.0.

**Review by jorindevandevis — APPROVED** [review]
This works very well, I have tested it for all BM models. Thanks a lot!

**Comment by og113** [comment]
Thanks Jorinde for your comments. This helped me realise that the loading of the new config parameter wasn't working (so all were using the default None). This has now been fixed.

**Pull request merged**
