### PR TITLE
xSM collision file

### PR DESCRIPTION
**Pull request by benoitlaurent96**
Just added the collision files with N=21 for top and gluons in xSM and manySinglets.

### CODE REVIEW

**Review by og113 — CHANGES_REQUESTED** [review]
Tested and the numbers seems sensible. I have one suggestion, can you add to the `docs/source/examples.rst` file, something like the following, to alert users to the existence of these files:
```
The Python files for the models can be viewed at the links below. They can also be
found at the `WallGo GitHub repo <https://github.com/Wall-Go/WallGo/tree/main/Models>`_
together with some pre-computed collision integrals.
```

**Review by og113 — COMMENTED** [review]
So, these files are ~25 MB. If, in the future, we make further versions of them (or other such files), then each time there is a new version we add ~25 MB to the repo, because the binary files cannot be properly followed with git. Currently our `.git/` directory is already 59MB, and this is probably mostly a few .hdf5 files being tracked. I think a better solution than adding these files with git might be to add them with git-lfs (https://git-lfs.com/). For a short discussion, see https://stackoverflow.com/questions/35575400/what-is-the-advantage-of-git-lfs. What do you think? If you agree, you would need to make a new PR, adding the same files with git-lfs instead of plain git.

**Comment by benoitlaurent96** [comment]
> So, these files are ~25 MB. If, in the future, we make further versions of them (or other such files), then each time there is a new version we add ~25 MB to the repo, because the binary files cannot be properly followed with git. Currently our `.git/` directory is already 59MB, and this is probably mostly a few .hdf5 files being tracked. I think a better solution than adding these files with git might be to add them with git-lfs (https://git-lfs.com/). For a short discussion, see https://stackoverflow.com/questions/35575400/what-is-the-advantage-of-git-lfs. What do you think? If you agree, you would need to make a new PR, adding the same files with git-lfs instead of plain git.

That's probably a good idea. So how would that work exactly? Should I first remove all the .hdf5 from the repo and then run something like "git lfs track '*.hdf5'".
By the way, when I do "pip install WallGo", does that download these files as well, or only what's in src?

**Comment by benoitlaurent96** [comment]
I think it works, but I'm not sure how to verify it. Does it look good to you (apart from the merge conflict)?

**Comment by og113** [comment]
Nice. Yes, it has worked for me. The only thing is, because the files were added in commits b37d4a178da1b303fd83dc43ec13b12c0a6e3670 and bf08e871be4cc8a4384f867a0c9b05a127909d27, even though they were removed in a later commit, they will still enter the commit history, and hence contribute to the size of the .git folder. So, I think it would be better to redo this git-lfs stuff on a new branch off main. Otherwise, I think it all looks good.

**Comment by benoitlaurent96** [comment]
Ok no problem. It's now on the PR #332.

**Pull request closed without merging**
