### PR TITLE
Sphinx GitHub pages

### PR DESCRIPTION
**Pull request by og113**
- Got the GitHub pages working, see https://wall-go.github.io/WallGo/
- Updated the README with links and following some defaultish start (https://github.com/conda-forge/bubbledet-feedstock)

### CODE REVIEW

**Comment by jorindevandevis** [comment]
I'm unfortunately getting a 404 error when I click the GitHub pages link. Is that just because this is not on main yet?

**Comment by og113** [comment]
Hmm, the pages were working before...

**Comment by og113** [comment]
GitHub reran the "pages build and deployment" action, and this broke the GitHub pages. I am not sure what went wrong. The ReadTheDocs pages worked out of the box: https://wallgo.readthedocs.io/

**Comment by jorindevandevis** [comment]
That's annoying. The ones on readthedocs look good. It's also an option to keep those.
Btw, the license looks a bit funny, because words like "and", "for" and "or" are colored

**Comment by og113** [comment]
I got the GitHub pages to work at some point, but then they broke again, and I haven't managed to get them working again. I'm tempted to dump PR #306 and replace it with a new one which just uses readthedocs, as that works out of the box.

**Comment by jorindevandevis** [comment]
Sounds like a reasonable solution to me

**Pull request closed without merging**
